#define ALLTYPE(V) \
V(kQuery) \
V(kSimpleStatement) \
V(kAlterStatement) \
V(kAlterDatabase) \
V(kAlterEvent) \
V(kAlterLogfileGroup) \
V(kAlterLogfileGroupOptions) \
V(kAlterLogfileGroupOption) \
V(kAlterServer) \
V(kAlterTable) \
V(kAlterTableActions) \
V(kAlterCommandList) \
V(kAlterCommandsModifierList) \
V(kStandaloneAlterCommands) \
V(kAlterPartition) \
V(kAlterList) \
V(kAlterCommandsModifier) \
V(kAlterListItem) \
V(kPlace) \
V(kRestrict) \
V(kAlterOrderList) \
V(kAlterAlgorithmOption) \
V(kAlterLockOption) \
V(kIndexLockAndAlgorithm) \
V(kWithValidation) \
V(kRemovePartitioning) \
V(kAllOrPartitionNameList) \
V(kAlterTablespace) \
V(kAlterUndoTablespace) \
V(kUndoTableSpaceOptions) \
V(kUndoTableSpaceOption) \
V(kAlterTablespaceOptions) \
V(kAlterTablespaceOption) \
V(kChangeTablespaceOption) \
V(kAlterView) \
V(kViewTail) \
V(kViewSelect) \
V(kViewCheckOption) \
V(kCreateStatement) \
V(kCreateDatabase) \
V(kCreateDatabaseOption) \
V(kCreateTable) \
V(kTableElementList) \
V(kTableElement) \
V(kDuplicateAsQueryExpression) \
V(kQueryExpressionOrParens) \
V(kCreateRoutine) \
V(kCreateProcedure) \
V(kCreateFunction) \
V(kCreateUdf) \
V(kRoutineCreateOption) \
V(kRoutineAlterOptions) \
V(kRoutineOption) \
V(kCreateIndex) \
V(kIndexNameAndType) \
V(kCreateIndexTarget) \
V(kCreateLogfileGroup) \
V(kLogfileGroupOptions) \
V(kLogfileGroupOption) \
V(kCreateServer) \
V(kServerOptions) \
V(kServerOption) \
V(kCreateTablespace) \
V(kCreateUndoTablespace) \
V(kTsDataFileName) \
V(kTsDataFile) \
V(kTablespaceOptions) \
V(kTablespaceOption) \
V(kTsOptionInitialSize) \
V(kTsOptionUndoRedoBufferSize) \
V(kTsOptionAutoextendSize) \
V(kTsOptionMaxSize) \
V(kTsOptionExtentSize) \
V(kTsOptionNodegroup) \
V(kTsOptionEngine) \
V(kTsOptionWait) \
V(kTsOptionComment) \
V(kTsOptionFileblockSize) \
V(kTsOptionEncryption) \
V(kCreateView) \
V(kViewReplaceOrAlgorithm) \
V(kViewAlgorithm) \
V(kViewSuid) \
V(kCreateTrigger) \
V(kTriggerFollowsPrecedesClause) \
V(kCreateEvent) \
V(kCreateRole) \
V(kCreateSpatialReference) \
V(kSrsAttribute) \
V(kDropStatement) \
V(kDropDatabase) \
V(kDropEvent) \
V(kDropFunction) \
V(kDropProcedure) \
V(kDropIndex) \
V(kDropLogfileGroup) \
V(kDropLogfileGroupOption) \
V(kDropServer) \
V(kDropTable) \
V(kDropTableSpace) \
V(kDropTrigger) \
V(kDropView) \
V(kDropRole) \
V(kDropSpatialReference) \
V(kDropUndoTablespace) \
V(kRenameTableStatement) \
V(kRenamePair) \
V(kTruncateTableStatement) \
V(kImportStatement) \
V(kCallStatement) \
V(kDeleteStatement) \
V(kPartitionDelete) \
V(kDeleteStatementOption) \
V(kDoStatement) \
V(kHandlerStatement) \
V(kHandlerReadOrScan) \
V(kInsertStatement) \
V(kInsertLockOption) \
V(kInsertFromConstructor) \
V(kFields) \
V(kInsertValues) \
V(kInsertQueryExpression) \
V(kValueList) \
V(kValues) \
V(kValuesReference) \
V(kInsertUpdateList) \
V(kLoadStatement) \
V(kDataOrXml) \
V(kXmlRowsIdentifiedBy) \
V(kLoadDataFileTail) \
V(kLoadDataFileTargetList) \
V(kFieldOrVariableList) \
V(kReplaceStatement) \
V(kSelectStatement) \
V(kSelectStatementWithInto) \
V(kQueryExpression) \
V(kQueryExpressionBody) \
V(kQueryExpressionParens) \
V(kQueryPrimary) \
V(kQuerySpecification) \
V(kSubquery) \
V(kQuerySpecOption) \
V(kLimitClause) \
V(kSimpleLimitClause) \
V(kLimitOptions) \
V(kLimitOption) \
V(kIntoClause) \
V(kProcedureAnalyseClause) \
V(kHavingClause) \
V(kWindowClause) \
V(kWindowDefinition) \
V(kWindowSpec) \
V(kWindowSpecDetails) \
V(kWindowFrameClause) \
V(kWindowFrameUnits) \
V(kWindowFrameExtent) \
V(kWindowFrameStart) \
V(kWindowFrameBetween) \
V(kWindowFrameBound) \
V(kWindowFrameExclusion) \
V(kWithClause) \
V(kCommonTableExpression) \
V(kGroupByClause) \
V(kOlapOption) \
V(kOrderClause) \
V(kDirection) \
V(kFromClause) \
V(kTableReferenceList) \
V(kTableValueConstructor) \
V(kExplicitTable) \
V(kRowValueExplicit) \
V(kSelectOption) \
V(kLockingClauseList) \
V(kLockingClause) \
V(kLockStrengh) \
V(kLockedRowAction) \
V(kSelectItemList) \
V(kSelectItem) \
V(kSelectAlias) \
V(kWhereClause) \
V(kTableReference) \
V(kEscapedTableReference) \
V(kJoinedTable) \
V(kNaturalJoinType) \
V(kInnerJoinType) \
V(kOuterJoinType) \
V(kTableFactor) \
V(kSingleTable) \
V(kSingleTableParens) \
V(kDerivedTable) \
V(kTableReferenceListParens) \
V(kTableFunction) \
V(kColumnsClause) \
V(kJtColumn) \
V(kOnEmptyOrError) \
V(kOnEmpty) \
V(kOnError) \
V(kJtOnResponse) \
V(kUnionOption) \
V(kTableAlias) \
V(kIndexHintList) \
V(kIndexHint) \
V(kIndexHintType) \
V(kKeyOrIndex) \
V(kConstraintKeyType) \
V(kIndexHintClause) \
V(kIndexList) \
V(kIndexListElement) \
V(kUpdateStatement) \
V(kTransactionOrLockingStatement) \
V(kTransactionStatement) \
V(kBeginWork) \
V(kTransactionCharacteristic) \
V(kSavepointStatement) \
V(kLockStatement) \
V(kLockItem) \
V(kLockOption) \
V(kXaStatement) \
V(kXaConvert) \
V(kXid) \
V(kReplicationStatement) \
V(kResetOption) \
V(kMasterResetOptions) \
V(kReplicationLoad) \
V(kChangeMaster) \
V(kChangeMasterOptions) \
V(kMasterOption) \
V(kPrivilegeCheckDef) \
V(kTablePrimaryKeyCheckDef) \
V(kMasterTlsCiphersuitesDef) \
V(kMasterFileDef) \
V(kServerIdList) \
V(kChangeReplication) \
V(kFilterDefinition) \
V(kFilterDbList) \
V(kFilterTableList) \
V(kFilterStringList) \
V(kFilterWildDbTableString) \
V(kFilterDbPairList) \
V(kSlave) \
V(kSlaveUntilOptions) \
V(kSlaveConnectionOptions) \
V(kSlaveThreadOptions) \
V(kSlaveThreadOption) \
V(kGroupReplication) \
V(kPreparedStatement) \
V(kExecuteStatement) \
V(kExecuteVarList) \
V(kCloneStatement) \
V(kDataDirSSL) \
V(kSsl) \
V(kAccountManagementStatement) \
V(kAlterUser) \
V(kAlterUserTail) \
V(kUserFunction) \
V(kCreateUser) \
V(kCreateUserTail) \
V(kDefaultRoleClause) \
V(kRequireClause) \
V(kConnectOptions) \
V(kAccountLockPasswordExpireOptions) \
V(kDropUser) \
V(kGrant) \
V(kGrantTargetList) \
V(kGrantOptions) \
V(kExceptRoleList) \
V(kWithRoles) \
V(kGrantAs) \
V(kVersionedRequireClause) \
V(kRenameUser) \
V(kRevoke) \
V(kOnTypeTo) \
V(kAclType) \
V(kRoleOrPrivilegesList) \
V(kRoleOrPrivilege) \
V(kGrantIdentifier) \
V(kRequireList) \
V(kRequireListElement) \
V(kGrantOption) \
V(kSetRole) \
V(kRoleList) \
V(kRole) \
V(kTableAdministrationStatement) \
V(kHistogram) \
V(kCheckOption) \
V(kRepairType) \
V(kInstallUninstallStatment) \
V(kSetStatement) \
V(kStartOptionValueList) \
V(kTransactionCharacteristics) \
V(kTransactionAccessMode) \
V(kIsolationLevel) \
V(kOptionValueListContinued) \
V(kOptionValueNoOptionType) \
V(kOptionValue) \
V(kSetSystemVariable) \
V(kStartOptionValueListFollowingOptionType) \
V(kOptionValueFollowingOptionType) \
V(kSetExprOrDefault) \
V(kShowStatement) \
V(kShowCommandType) \
V(kNonBlocking) \
V(kFromOrIn) \
V(kInDb) \
V(kProfileType) \
V(kOtherAdministrativeStatement) \
V(kKeyCacheListOrParts) \
V(kKeyCacheList) \
V(kAssignToKeycache) \
V(kAssignToKeycachePartition) \
V(kCacheKeyList) \
V(kKeyUsageElement) \
V(kKeyUsageList) \
V(kFlushOption) \
V(kLogType) \
V(kFlushTables) \
V(kFlushTablesOptions) \
V(kPreloadTail) \
V(kPreloadList) \
V(kPreloadKeys) \
V(kAdminPartition) \
V(kResourceGroupManagement) \
V(kCreateResourceGroup) \
V(kResourceGroupVcpuList) \
V(kVcpuNumOrRange) \
V(kResourceGroupPriority) \
V(kResourceGroupEnableDisable) \
V(kAlterResourceGroup) \
V(kSetResourceGroup) \
V(kThreadIdList) \
V(kDropResourceGroup) \
V(kUtilityStatement) \
V(kDescribeStatement) \
V(kExplainStatement) \
V(kExplainableStatement) \
V(kHelpCommand) \
V(kUseCommand) \
V(kRestartServer) \
V(kExprOr) \
V(kExprNot) \
V(kExprIs) \
V(kExprAnd) \
V(kExprXor) \
V(kPrimaryExprPredicate) \
V(kPrimaryExprCompare) \
V(kPrimaryExprAllAny) \
V(kPrimaryExprIsNull) \
V(kCompOp) \
V(kPredicate) \
V(kPredicateExprIn) \
V(kPredicateExprBetween) \
V(kPredicateExprLike) \
V(kPredicateExprRegex) \
V(kBitExpr) \
V(kSimpleExprConvert) \
V(kSimpleExprVariable) \
V(kSimpleExprCast) \
V(kSimpleExprUnary) \
V(kSimpleExprOdbc) \
V(kSimpleExprRuntimeFunction) \
V(kSimpleExprFunction) \
V(kSimpleExprCollate) \
V(kSimpleExprMatch) \
V(kSimpleExprWindowingFunction) \
V(kSimpleExprBinary) \
V(kSimpleExprColumnRef) \
V(kSimpleExprParamMarker) \
V(kSimpleExprSum) \
V(kSimpleExprConvertUsing) \
V(kSimpleExprSubQuery) \
V(kSimpleExprGroupingOperation) \
V(kSimpleExprNot) \
V(kSimpleExprValues) \
V(kSimpleExprDefault) \
V(kSimpleExprList) \
V(kSimpleExprInterval) \
V(kSimpleExprCase) \
V(kSimpleExprConcat) \
V(kSimpleExprLiteral) \
V(kArrayCast) \
V(kJsonOperator) \
V(kSumExpr) \
V(kGroupingOperation) \
V(kWindowFunctionCall) \
V(kWindowingClause) \
V(kLeadLagInfo) \
V(kNullTreatment) \
V(kJsonFunction) \
V(kInSumExpr) \
V(kIdentListArg) \
V(kIdentList) \
V(kFulltextOptions) \
V(kRuntimeFunctionCall) \
V(kGeometryFunction) \
V(kTimeFunctionParameters) \
V(kFractionalPrecision) \
V(kWeightStringLevels) \
V(kWeightStringLevelListItem) \
V(kDateTimeTtype) \
V(kTrimFunction) \
V(kSubstringFunction) \
V(kFunctionCall) \
V(kUdfExprList) \
V(kUdfExpr) \
V(kVariable) \
V(kUserVariable) \
V(kSystemVariable) \
V(kInternalVariableName) \
V(kWhenExpression) \
V(kThenExpression) \
V(kElseExpression) \
V(kCastType) \
V(kExprList) \
V(kCharset) \
V(kNotRule) \
V(kNot2Rule) \
V(kInterval) \
V(kIntervalTimeStamp) \
V(kExprListWithParentheses) \
V(kExprWithParentheses) \
V(kSimpleExprWithParentheses) \
V(kOrderList) \
V(kOrderExpression) \
V(kGroupList) \
V(kGroupingExpression) \
V(kChannel) \
V(kCompoundStatement) \
V(kReturnStatement) \
V(kIfStatement) \
V(kIfBody) \
V(kThenStatement) \
V(kCompoundStatementList) \
V(kCaseStatement) \
V(kElseStatement) \
V(kLabeledBlock) \
V(kUnlabeledBlock) \
V(kLabel) \
V(kBeginEndBlock) \
V(kLabeledControl) \
V(kUnlabeledControl) \
V(kLoopBlock) \
V(kWhileDoBlock) \
V(kRepeatUntilBlock) \
V(kSpDeclarations) \
V(kSpDeclaration) \
V(kVariableDeclaration) \
V(kConditionDeclaration) \
V(kSpCondition) \
V(kSqlstate) \
V(kHandlerDeclaration) \
V(kHandlerCondition) \
V(kCursorDeclaration) \
V(kIterateStatement) \
V(kLeaveStatement) \
V(kGetDiagnostics) \
V(kSignalAllowedExpr) \
V(kStatementInformationItem) \
V(kConditionInformationItem) \
V(kSignalInformationItemName) \
V(kSignalStatement) \
V(kResignalStatement) \
V(kSignalInformationItem) \
V(kCursorOpen) \
V(kCursorClose) \
V(kCursorFetch) \
V(kSchedule) \
V(kColumnDefinition) \
V(kCheckOrReferences) \
V(kCheckConstraint) \
V(kConstraintEnforcement) \
V(kTableConstraintDef) \
V(kConstraintName) \
V(kFieldDefinition) \
V(kColumnAttribute) \
V(kColumnFormat) \
V(kStorageMedia) \
V(kGcolAttribute) \
V(kReferences) \
V(kDeleteOption) \
V(kKeyList) \
V(kKeyPart) \
V(kKeyListWithExpression) \
V(kKeyPartOrExpression) \
V(kKeyListVariants) \
V(kIndexType) \
V(kIndexOption) \
V(kCommonIndexOption) \
V(kVisibility) \
V(kIndexTypeClause) \
V(kFulltextIndexOption) \
V(kSpatialIndexOption) \
V(kDataTypeDefinition) \
V(kDataType) \
V(kNchar) \
V(kRealType) \
V(kFieldLength) \
V(kFieldOptions) \
V(kCharsetWithOptBinary) \
V(kAscii) \
V(kUnicode) \
V(kWsNumCodepoints) \
V(kTypeDatetimePrecision) \
V(kCharsetName) \
V(kCollationName) \
V(kCreateTableOptions) \
V(kCreateTableOptionsSpaceSeparated) \
V(kCreateTableOption) \
V(kTernaryOption) \
V(kDefaultCollation) \
V(kDefaultEncryption) \
V(kDefaultCharset) \
V(kPartitionClause) \
V(kPartitionDefKey) \
V(kPartitionDefHash) \
V(kPartitionDefRangeList) \
V(kSubPartitions) \
V(kPartitionKeyAlgorithm) \
V(kPartitionDefinitions) \
V(kPartitionDefinition) \
V(kPartitionValuesIn) \
V(kPartitionOption) \
V(kSubpartitionDefinition) \
V(kPartitionValueItemListParen) \
V(kPartitionValueItem) \
V(kDefinerClause) \
V(kIfExists) \
V(kIfNotExists) \
V(kProcedureParameter) \
V(kFunctionParameter) \
V(kCollate) \
V(kTypeWithOptCollate) \
V(kSchemaIdentifierPair) \
V(kViewRefList) \
V(kUpdateList) \
V(kUpdateElement) \
V(kCharsetClause) \
V(kFieldsClause) \
V(kFieldTerm) \
V(kLinesClause) \
V(kLineTerm) \
V(kUserList) \
V(kCreateUserList) \
V(kAlterUserList) \
V(kCreateUserEntry) \
V(kAlterUserEntry) \
V(kRetainCurrentPassword) \
V(kDiscardOldPassword) \
V(kReplacePassword) \
V(kUserIdentifierOrText) \
V(kUser) \
V(kLikeClause) \
V(kLikeOrWhere) \
V(kOnlineOption) \
V(kNoWriteToBinLog) \
V(kUsePartition) \
V(kFieldIdentifier) \
V(kColumnName) \
V(kColumnInternalRef) \
V(kColumnInternalRefList) \
V(kColumnRef) \
V(kInsertIdentifier) \
V(kIndexName) \
V(kIndexRef) \
V(kTableWild) \
V(kSchemaName) \
V(kSchemaRef) \
V(kProcedureName) \
V(kProcedureRef) \
V(kFunctionName) \
V(kFunctionRef) \
V(kTriggerName) \
V(kTriggerRef) \
V(kViewName) \
V(kViewRef) \
V(kTablespaceName) \
V(kTablespaceRef) \
V(kLogfileGroupName) \
V(kLogfileGroupRef) \
V(kEventName) \
V(kEventRef) \
V(kUdfName) \
V(kServerName) \
V(kServerRef) \
V(kEngineRef) \
V(kTableName) \
V(kFilterTableRef) \
V(kTableRefWithWildcard) \
V(kTableRef) \
V(kTableRefList) \
V(kTableAliasRefList) \
V(kParameterName) \
V(kLabelIdentifier) \
V(kLabelRef) \
V(kRoleIdentifier) \
V(kRoleRef) \
V(kPluginRef) \
V(kComponentRef) \
V(kResourceGroupRef) \
V(kWindowName) \
V(kPureIdentifier) \
V(kIdentifier) \
V(kIdentifierList) \
V(kIdentifierListWithParentheses) \
V(kQualifiedIdentifier) \
V(kSimpleIdentifier) \
V(kDotIdentifier) \
V(kUlong_number) \
V(kReal_ulong_number) \
V(kUlonglong_number) \
V(kReal_ulonglong_number) \
V(kLiteral) \
V(kSignedLiteral) \
V(kStringList) \
V(kTextStringLiteral) \
V(kTextString) \
V(kTextStringHash) \
V(kTextLiteral) \
V(kTextStringNoLinebreak) \
V(kTextStringLiteralList) \
V(kNumLiteral) \
V(kBoolLiteral) \
V(kNullLiteral) \
V(kTemporalLiteral) \
V(kFloatOptions) \
V(kStandardFloatOptions) \
V(kPrecision) \
V(kTextOrIdentifier) \
V(kLValueIdentifier) \
V(kRoleIdentifierOrText) \
V(kSizeNumber) \
V(kParentheses) \
V(kEqual) \
V(kOptionType) \
V(kVarIdentType) \
V(kSetVarIdentType) \
V(kIdentifierKeyword) \
V(kIdentifierKeywordsAmbiguous1RolesAndLabels) \
V(kIdentifierKeywordsAmbiguous2Labels) \
V(kLabelKeyword) \
V(kIdentifierKeywordsAmbiguous3Roles) \
V(kIdentifierKeywordsUnambiguous) \
V(kRoleKeyword) \
V(kLValueKeyword) \
V(kIdentifierKeywordsAmbiguous4SystemVariables) \
V(kRoleOrIdentifierKeyword) \
V(kRoleOrLabelKeyword) \
V(kIntLiteral) \
V(kFloatLiteral) \
V(kStringLiteral) \
V(kBooleanLiteral) \
V(kIdentifierRule) \
V(kStmtList) \
V(kUnknown)


#define ALLDATAFLAG(V) \
  V(kUse) \
  V(kMapToClosestOne) \
  V(kNoSplit) \
  V(kGlobal) \
  V(kReplace) \
  V(kUndefine) \
  V(kAlias) \
  V(kMapToAll) \
  V(kDefine) \
  V(kNoModi) \
  V(kUseDefine)  /* Immediate use of the defined column. In PRIMARY KEY(), INDEX() etc.*/ \
  V(kFlagUnknown) \



#define ALLDATATYPE(V) \
  V(kDataWhatever) \
  V(kDataTableName) \
  V(kDataColumnName) \
  V(kDataViewName) \
  V(kDataFunctionName) \
  V(kDataFunctionParams) \
  V(kDataPragmaKey) \
  V(kDataPragmaValue) \
  V(kDataTableSpaceName) \
  V(kDataUndoTableSpaceName) \
  V(kDataSequenceName) \
  V(kDataExtensionName) \
  V(kDataRoleName) \
  V(kDataSchemaName) \
  V(kDataDatabase) \
  V(kDataTriggerName) \
  V(kDataWindowName) \
  V(kDataTriggerFunction) \
  V(kDataDomainName) \
  V(kDataAliasName) \
  V(kDataFixLater) \
  V(kDataIndexName) \
  V(kDataUserName) \
  V(kDataHostName) \
  V(kDataCollate) \
  V(kDataCharsetName) \
  V(kDataProcedureName) \
  V(kDataProcedureParams) \
  V(kDataServerName) \
  V(kDataWrapperName) \
  V(kDataSavePoint) \
  V(kDataGroupName) \
  V(kDataLogFileGroupName) \
  V(kDataFileSystem) \
  V(kDataSystemVarName) \
  V(kDataAliasTableName) \
  V(kDataTableNameFollow) \
  V(kDataColumnNameFollow) \
  V(kDataConstraintName) \
  V(kDataVarName) \
  V(kDataStmtName) \
  V(kDataPluginName) \
  V(kDataComponentName) \
  V(kDataEngineName) \
  V(kDataParserName) \
  V(kDataForeignKey) \
  V(kDataPartitionName) \
  V(kDataDatabaseFollow) \
  V(kDataLabelName) \
  V(kDataLiteral) \
  V(kDataEventName) \
  



#define ALLSPECIALTERMTOKENTYPE(V) \
  V(IDENTIFIER) \
  V(SINGLE_QUOTED_TEXT) \
  V(DOUBLE_QUOTED_TEXT) \
  V(HEX_NUMBER) \
  V(BIN_NUMBER) \
  V(NCHAR_TEXT) \
  V(INT_NUMBER) \
  V(LONG_NUMBER) \
  V(ULONGLONG_NUMBER) \
  V(DECIMAL_NUMBER) \
  V(FLOAT_NUMBER) \
  V(TRUE_SYMBOL) \
  V(FALSE_SYMBOL) \
  V(BACK_TICK_QUOTED_ID) \
  

